name: Java CI with Maven

on:
    push:
        branches: [ "feat/dev" ]
    #pull_request:
        #branches: [ "main" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout cod
              uses: actions/checkout@v3

